### PR TITLE
fix: optimize query to fetch gloss suggestions

### LINKED ISSUE #224: production requests take a while to complete and fail infrequently
**Describe the bug**
Some requests are taking several seconds to complete and some are timing out with a 500 status code. Server logs show this error:
```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 1)
```

**To Reproduce**

1. Load translation view in the production site
2. Check the network tab in the dev tools
3. Look for long running requests

**Expected behavior**
Requests should be quicker to execute

### PR DESCRIPTION
**Pull request by arrocke**
## What has changed

The queries for loading suggestions were creating an inefficiency because we were firing off one query per word. Since they were in parallel, prisma was getting backed up and couldn't complete the requests before they timed out.

This now loads all of the data for that route with a single query that is pretty efficient. Testing on my local device reduced the time from ~2 seconds to ~0.6 seconds.

## Connected Issues

closes #224 

## QA Steps

Just need to confirm that gloss suggestions load in descending order of use

## Post-Deployment

- [x] Nothing required

### CODE REVIEW

**Comment by Pertempto** [comment]
For some reason I'm getting a 404 error on the glosses route for any language except English. (It works great in English)

File: packages/api/pages/api/languages/[code]/verses/[verseId]/glosses.ts [hunk 1]
```diff
@@ -13,71 +17,49 @@ export default createRoute<{ code: string; verseId: string }>()
...
-                  .map((doc) => doc.gloss)
-                  .filter((gloss): gloss is string => !!gloss),
-                state: state ?? GlossState.Unapproved,
-              };
-            }),
-          });
-          return;
-        }
+      if (words.length === 0) {
+        res.notFound();
```
Comment (Pertempto) [inline packages/api/pages/api/languages/[code]/verses/[verseId]/glosses.ts:61]: I added a debug message to confirm, this is where the 404s are originating from.

File: packages/api/pages/api/languages/[code]/verses/[verseId]/glosses.ts [hunk 2]
```diff
@@ -37,28 +37,28 @@ export default createRoute<{ code: string; verseId: string }>()
...
+          "VerseWord"."id" as "wordId",
+          COALESCE("Gloss"."gloss", '') AS "gloss",
+          COALESCE("Suggestion"."suggestions", '{}') AS "suggestions",
+          COALESCE("Gloss"."state", 'UNAPPROVED') AS "state"
+        FROM "VerseWord"
         LEFT OUTER JOIN "Suggestion" ON "VerseWord"."id" = "Suggestion"."id"
-        JOIN "Gloss" ON "VerseWord"."id" = "wordId"
-        WHERE "Gloss"."languageId" = ${language.id}::uuid 
+        LEFT OUTER JOIN "Gloss" ON "VerseWord"."id" = "wordId"
+          AND "Gloss"."languageId" = ${language.id}::uuid
```
Comment (arrocke) [inline packages/api/pages/api/languages/[code]/verses/[verseId]/glosses.ts:55]: I missed two things that ensure that an array of words is always returned if the verse exists even if there are no glosses for the verse.
* I needed to use a LEFT OUTER JOIN for glosses in the case that they don't exist.
* And then I needed to move the WHERE into the join so that it only governs which glosses are joined rather than which rows are returned in the results.

**Comment by Pertempto** [comment]
I'm not sure how exactly, but I was just testing entering glosses in a verse and all of a sudden I got this error:
image



I believe this is the data from the offending glosses request. It appears that `null` got into the `suggestions` array somehow.


<details>

<summary>Gloss data</summary>

```
{
    "data": [
        {
            "wordId": "4000100301",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100302",
            "gloss": "",
            "suggestions": [
                "moreover"
            ],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100303",
            "gloss": "def",
            "suggestions": [
                "abc",
                "def",
                "ghi",
                "mno",
                null
            ],
            "state": "APPROVED"
        },
        {
            "wordId": "4000100304",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100305",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100306",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100307",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100308",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100309",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100310",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100311",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100312",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100313",
            "gloss": "",
            "suggestions": [
                "moreover"
            ],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100314",
            "gloss": "",
            "suggestions": [
                "abc",
                "def",
                "ghi",
                "mno",
                null
            ],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100315",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100316",
            "gloss": "Test",
            "suggestions": [
                "Test"
            ],
            "state": "APPROVED"
        },
        {
            "wordId": "4000100317",
            "gloss": "ab",
            "suggestions": [
                "ab"
            ],
            "state": "APPROVED"
        },
        {
            "wordId": "4000100318",
            "gloss": "moreover",
            "suggestions": [
                "moreover"
            ],
            "state": "APPROVED"
        },
        {
            "wordId": "4000100319",
            "gloss": "",
            "suggestions": [
                "abc",
                "def",
                "ghi",
                "mno",
                null
            ],
            "state": "APPROVED"
        },
        {
            "wordId": "4000100320",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        },
        {
            "wordId": "4000100321",
            "gloss": "",
            "suggestions": [],
            "state": "UNAPPROVED"
        }
    ]
}
```


</details>

**Comment by arrocke** [comment]
Ok, I think I addressed this. The issue was that empty glosses where allowed to be marked as approved.

**Review by Pertempto — CHANGES_REQUESTED** [review]
Now we have a bigger issue - every time you input a gloss and press "enter", the frontend sends 2 PATCH requests to the backend - one with an empty gloss marked "unapproved", and one with the correct gloss marked "approved". The end result varies on which request completes second, so about 50% the gloss is correctly entered, and the rest of the time it is left unapproved.


image
image

**Review by Pertempto — APPROVED** [review]
I like how this combines with the changes from https://github.com/arrocke/gloss-translation/pull/232 so that the most common gloss for a word becomes the automatic suggestion. 👍🏽
