### PR TITLE
fix: note phrases join

### LINKED ISSUE #398: bug: fix notes phrase join
**Describe the bug**
The raw database query in `languages/[code]/verses/[verseId]/notes.ts` contains a bug where it will return words attached to phrases which are in a different language.

**To Reproduce**
1. Reseed the database.
2. Run the database query in pgAdmin. Note the results
3. Add a translator note to a word
4. Run the database query in pgAdmin. Confirm there is a duplicate row.

**Expected behavior**
There should be no duplicate rows.

**Additional context**

### PR DESCRIPTION
**Pull request by tycebrown**
## What has changed
The raw database query in `notes.ts` has been fixed. Now, it uses a `LEFT JOIN LATERL SELECT` to join the words and phrases.

## Connected Issues

closes #398

## QA Steps

1. Test the query in pgAdmin or add a `console.log` in `notes.ts`. Observe if there are any duplicates in the results.

## Post-Deployment

- [x] Nothing required

### CODE REVIEW

File: packages/api/pages/api/languages/[code]/verses/[verseId]/notes.ts [hunk 1]
```diff
@@ -35,9 +35,12 @@ export default createRoute<{ code: string; verseId: string }>()
           COALESCE(fn."content", '') AS "footnoteContent"
         FROM "Word" AS w
 
-        LEFT JOIN "PhraseWord" AS phw ON phw."wordId" = w.id
-        LEFT JOIN "Phrase" AS ph ON ph.id = phw."phraseId"
-          AND ph."languageId" = ${language.id}::uuid
+        LEFT JOIN LATERAL (
+          SELECT phw."wordId", ph.id FROM "PhraseWord" AS phw
```
Comment (arrocke) [inline packages/api/pages/api/languages/[code]/verses/[verseId]/notes.ts]: We are only using the phrase id once this is joined, so we can remove the word id from the select here
```suggestion
          SELECT ph.id FROM "PhraseWord" AS phw
```

**Review by arrocke — APPROVED** [review]
One suggestion here. I'm going to commit it and merge. Thanks for taking care of this
